# Generated by Django 2.0.3 on 2018-06-22 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='avatar',
            field=models.FileField(default='static/avatars/default.png', upload_to='media/avatars/', verbose_name='头像'),
        ),
    ]
